import { Geist, Geist_Mono } from "next/font/google";
import { 
  Tenor_Sans, 
  Sorts_Mill_Goudy, 
  EB_Garamond, 
  Spectral, 
  Merriweather_Sans 
} from "next/font/google";
import "./globals.css";
import SearchBar from "./components/SearchBar";
import hotelData from "./components/data.json"
import Link from "next/link";
import Image from "next/image";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const tenorSans = Tenor_Sans({
  variable: "--font-tenor-sans",
  subsets: ["latin"],
  weight: "400",
});

const sortsMillGoudy = Sorts_Mill_Goudy({
  variable: "--font-sorts-mill-goudy",
  subsets: ["latin"],
  weight: "400",
});

const ebGaramond = EB_Garamond({
  variable: "--font-eb-garamond",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

const spectral = Spectral({
  variable: "--font-spectral",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

const merriweatherSans = Merriweather_Sans({
  variable: "--font-merriweather-sans",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const cities = [...new Set(hotelData.map(hotel => hotel.city))].sort();
  return (
    <html lang="en">
      <body
        className={`
          ${geistSans.variable} 
          ${geistMono.variable} 
          ${tenorSans.variable} 
          ${sortsMillGoudy.variable}
          ${ebGaramond.variable}
          ${spectral.variable}
          ${merriweatherSans.variable}
          antialiased
        `}
      >
        <header>
          <nav className="px-20 py-8">
            <Link href="/">
              <Image src="/logo.svg" alt="Stash Logo" width={200} height={40} />
            </Link>
          </nav>
        </header>
        <SearchBar cities={cities}/>
        {children}
      </body>
    </html>
  );
}
